### ISSUE TITLE
MetroTimer: добавить кнопку «Скопировать» у каждой колонки

### ISSUE THREAD

**Issue by alexkolodko** [agentyzmin/a3-tools#1]
@proggeo Скажи, а можно сделать у каждой колонки кнопку «Скопировать»? Чтобы оно копировало в буфер только одну колонку с форматированием.

**Comment by proggeo** [comment]
@alexkolodko думаю, що можна буде таке зробити.
завтра займусь цим.

**Comment by alexkolodko** [comment]
Я выбрал Кловскую, нажал кнопку. В буфер копируется инфа от Академгородка + инфа от Кловской.
